name: Testing

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod tidy
        working-directory: backend

      - name: unit
        run: make unit
        working-directory: backend

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate

      - name: Run migrations
        run: make migrateup
        working-directory: backend

      - name: integration
        run: make integration
        working-directory: backend

      - name: e2e
        run: make e2e; make e2e_bdd
        working-directory: backend